name: ml
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - pyqt=5.9.2
  - python=3.7.7
  - pip:
    - matplotlib==3.2.1
    - scipy==1.4.1
    - seaborn==0.10.0
    - spyder==4.1.2
    - spyder-kernels==1.9.0
    - statsmodels==0.11.1
    - sympy==1.5.1
    - tensorflow==2.0.0

